### PR TITLE
changes

### PR DESCRIPTION
**Pull request by MandarJoshi23**

### CODE REVIEW

**Review by akshay-at-bluepineapple — COMMENTED** [review]
review done

**Comment by sayali-more-bluepineapple** [comment]
change function name

**Review by sayali-more-bluepineapple — APPROVED** [review]

**Review by akshay-at-bluepineapple — CHANGES_REQUESTED** [review]
remove repetitive function

**Review by akshay-at-bluepineapple — APPROVED** [review]
accepted

**Pull request merged**
